apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
data:
  "settings.js": |-
    exports.brigadeApiURL = '{{ default "http://localhost:7744" .Values.brigade.apiServer }}'
    // End
