apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
data:
  "default.conf": |-
      server {
          listen       {{ .Values.service.internalPort }};
          server_name  localhost;

          # Proxy to API server
          location /v1/ {
              proxy_pass {{ .Values.brigade.apiServer }}/v1/;
          }

          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
              try_files $uri $uri/ /index.html;
          }
          
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
      }
